CURRENCIES = {
    "IRR": {"en": "Iranian Rial", "fa": "ریال ایران", "symbol": "﷼", "flag": "🇮🇷"},
    "USD": {"en": "US Dollar", "fa": "دلار آمریکا", "symbol": "$", "flag": "🇺🇸"},
    "EUR": {"en": "Euro", "fa": "یورو", "symbol": "€", "flag": "🇪🇺"},
    "GBP": {"en": "British Pound", "fa": "پوند بریتانیا", "symbol": "£", "flag": "🇬🇧"},
    "AED": {"en": "UAE Dirham", "fa": "درهم امارات", "symbol": "د.إ", "flag": "🇦🇪"},
    "TRY": {"en": "Turkish Lira", "fa": "لیر ترکیه", "symbol": "₺", "flag": "🇹🇷"},
    "CHF": {"en": "Swiss Franc", "fa": "فرانک سوئیس", "symbol": "CHF", "flag": "🇨🇭"},
    "CNY": {"en": "Chinese Yuan", "fa": "یوان چین", "symbol": "¥", "flag": "🇨🇳"},
    "JPY": {"en": "Japanese Yen", "fa": "ین ژاپن", "symbol": "¥", "flag": "🇯🇵"},
    "CAD": {"en": "Canadian Dollar", "fa": "دلار کانادا", "symbol": "C$", "flag": "🇨🇦"},
    "AUD": {"en": "Australian Dollar", "fa": "دلار استرالیا", "symbol": "A$", "flag": "🇦🇺"},
    "NZD": {"en": "New Zealand Dollar", "fa": "دلار نیوزلند", "symbol": "NZ$", "flag": "🇳🇿"},
    "SGD": {"en": "Singapore Dollar", "fa": "دلار سنگاپور", "symbol": "S$", "flag": "🇸🇬"},
    "INR": {"en": "Indian Rupee", "fa": "روپیه هند", "symbol": "₹", "flag": "🇮🇳"},
    "PKR": {"en": "Pakistani Rupee", "fa": "روپیه پاکستان", "symbol": "₨", "flag": "🇵🇰"},
    "IQD": {"en": "Iraqi Dinar", "fa": "دینار عراق", "symbol": "ع.د", "flag": "🇮🇶"},
    "SAR": {"en": "Saudi Riyal", "fa": "ریال عربستان", "symbol": "﷼", "flag": "🇸🇦"},
    "KWD": {"en": "Kuwaiti Dinar", "fa": "دینار کویت", "symbol": "د.ك", "flag": "🇰🇼"},
    "BHD": {"en": "Bahraini Dinar", "fa": "دینار بحرین", "symbol": ".د.ب", "flag": "🇧🇭"},
    "OMR": {"en": "Omani Rial", "fa": "ریال عمان", "symbol": "ر.ع.", "flag": "🇴🇲"},
    "QAR": {"en": "Qatari Riyal", "fa": "ریال قطر", "symbol": "ر.ق", "flag": "🇶🇦"},
    "KRW": {"en": "South Korean Won", "fa": "وون کره جنوبی", "symbol": "₩", "flag": "🇰🇷"},
    "DKK": {"en": "Danish Krone", "fa": "کرون دانمارک", "symbol": "kr", "flag": "🇩🇰"},
    "SEK": {"en": "Swedish Krona", "fa": "کرون سوئد", "symbol": "kr", "flag": "🇸🇪"},
    "NOK": {"en": "Norwegian Krone", "fa": "کرون نروژ", "symbol": "kr", "flag": "🇳🇴"},
    "RUB": {"en": "Russian Ruble", "fa": "روبل روسیه", "symbol": "₽", "flag": "🇷🇺"},
    "THB": {"en": "Thai Baht", "fa": "بات تایلند", "symbol": "฿", "flag": "🇹🇭"},
    "MYR": {"en": "Malaysian Ringgit", "fa": "رینگیت مالزی", "symbol": "RM", "flag": "🇲🇾"},
    "HKD": {"en": "Hong Kong Dollar", "fa": "دلار هنگ‌کنگ", "symbol": "HK$", "flag": "🇭🇰"},
    "AFN": {"en": "Afghan Afghani", "fa": "افغانی افغانستان", "symbol": "؋", "flag": "🇦🇫"},
    "AZN": {"en": "Azerbaijani Manat", "fa": "منات آذربایجان", "symbol": "₼", "flag": "🇦🇿"},
    "AMD": {"en": "Armenian Dram", "fa": "درام ارمنستان", "symbol": "֏", "flag": "🇦🇲"},
    "GEL": {"en": "Georgian Lari", "fa": "لاری گرجستان", "symbol": "₾", "flag": "🇬🇪"},
    "KGS": {"en": "Kyrgyzstani Som", "fa": "سوم قرقیزستان", "symbol": "сом", "flag": "🇰🇬"},
    "TJS": {"en": "Tajikistani Somoni", "fa": "سامانی تاجیکستان", "symbol": "SM", "flag": "🇹🇯"},
    "TMT": {"en": "Turkmenistani Manat", "fa": "منات ترکمنستان", "symbol": "T", "flag": "🇹🇲"},
    "SYP": {"en": "Syrian Pound", "fa": "لیر سوریه", "symbol": "£S", "flag": "🇸🇾"},
    # Europe
    "RON": {"en": "Romanian Leu", "fa": "لئو رومانی", "symbol": "lei", "flag": "🇷🇴"},
    "PLN": {"en": "Polish Zloty", "fa": "زلوتی لهستان", "symbol": "zł", "flag": "🇵🇱"},
    "CZK": {"en": "Czech Koruna", "fa": "کرون چک", "symbol": "Kč", "flag": "🇨🇿"},
    "HUF": {"en": "Hungarian Forint", "fa": "فورینت مجارستان", "symbol": "Ft", "flag": "🇭🇺"},
    "BGN": {"en": "Bulgarian Lev", "fa": "لو بلغارستان", "symbol": "лв", "flag": "🇧🇬"},
    "HRK": {"en": "Croatian Kuna", "fa": "کونا کرواسی", "symbol": "kn", "flag": "🇭🇷"},
    "RSD": {"en": "Serbian Dinar", "fa": "دینار صربستان", "symbol": "din.", "flag": "🇷🇸"},
    "UAH": {"en": "Ukrainian Hryvnia", "fa": "هریونیا اوکراین", "symbol": "₴", "flag": "🇺🇦"},
    "ISK": {"en": "Icelandic Krona", "fa": "کرون ایسلند", "symbol": "kr", "flag": "🇮🇸"},
    # Americas
    "BRL": {"en": "Brazilian Real", "fa": "رئال برزیل", "symbol": "R$", "flag": "🇧🇷"},
    "MXN": {"en": "Mexican Peso", "fa": "پزو مکزیک", "symbol": "MX$", "flag": "🇲🇽"},
    "ARS": {"en": "Argentine Peso", "fa": "پزو آرژانتین", "symbol": "AR$", "flag": "🇦🇷"},
    "CLP": {"en": "Chilean Peso", "fa": "پزو شیلی", "symbol": "CL$", "flag": "🇨🇱"},
    "COP": {"en": "Colombian Peso", "fa": "پزو کلمبیا", "symbol": "CO$", "flag": "🇨🇴"},
    # Africa
    "ZAR": {"en": "South African Rand", "fa": "رند آفریقای جنوبی", "symbol": "R", "flag": "🇿🇦"},
    "EGP": {"en": "Egyptian Pound", "fa": "پوند مصر", "symbol": "E£", "flag": "🇪🇬"},
    "NGN": {"en": "Nigerian Naira", "fa": "نایرا نیجریه", "symbol": "₦", "flag": "🇳🇬"},
    "MAD": {"en": "Moroccan Dirham", "fa": "درهم مراکش", "symbol": "د.م.", "flag": "🇲🇦"},
    "TND": {"en": "Tunisian Dinar", "fa": "دینار تونس", "symbol": "د.ت", "flag": "🇹🇳"},
    "KES": {"en": "Kenyan Shilling", "fa": "شیلینگ کنیا", "symbol": "KSh", "flag": "🇰🇪"},
    # Asia & Oceania
    "IDR": {"en": "Indonesian Rupiah", "fa": "روپیه اندونزی", "symbol": "Rp", "flag": "🇮🇩"},
    "PHP": {"en": "Philippine Peso", "fa": "پزو فیلیپین", "symbol": "₱", "flag": "🇵🇭"},
    "VND": {"en": "Vietnamese Dong", "fa": "دونگ ویتنام", "symbol": "₫", "flag": "🇻🇳"},
    "BDT": {"en": "Bangladeshi Taka", "fa": "تاکا بنگلادش", "symbol": "৳", "flag": "🇧🇩"},
    "LKR": {"en": "Sri Lankan Rupee", "fa": "روپیه سریلانکا", "symbol": "Rs", "flag": "🇱🇰"},
    "TWD": {"en": "New Taiwan Dollar", "fa": "دلار تایوان", "symbol": "NT$", "flag": "🇹🇼"},
    "JOD": {"en": "Jordanian Dinar", "fa": "دینار اردن", "symbol": "د.ا", "flag": "🇯🇴"},
    "LBP": {"en": "Lebanese Pound", "fa": "لیر لبنان", "symbol": "ل.ل", "flag": "🇱🇧"},
    "ILS": {"en": "Israeli Shekel", "fa": "شکل اسرائیل", "symbol": "₪", "flag": "🇮🇱"},
    "UZS": {"en": "Uzbekistani Som", "fa": "سوم ازبکستان", "symbol": "сўм", "flag": "🇺🇿"},
    "KZT": {"en": "Kazakhstani Tenge", "fa": "تنگه قزاقستان", "symbol": "₸", "flag": "🇰🇿"},
}

POPULAR_CURRENCIES = [
    "IRR", "USD", "EUR", "GBP", "AED", "TRY", "SAR", "CAD",
    "AUD", "CHF", "JPY", "CNY", "INR", "KWD", "RON", "BRL",
]
