CURRENCIES = {
    "IRR": {"en": "Iranian Rial", "fa": "ریال ایران", "symbol": "﷼", "flag": "🇮🇷", "cc": "ir"},
    "USD": {"en": "US Dollar", "fa": "دلار آمریکا", "symbol": "$", "flag": "🇺🇸", "cc": "us"},
    "EUR": {"en": "Euro", "fa": "یورو", "symbol": "€", "flag": "🇪🇺", "cc": "eu"},
    "GBP": {"en": "British Pound", "fa": "پوند بریتانیا", "symbol": "£", "flag": "🇬🇧", "cc": "gb"},
    "AED": {"en": "UAE Dirham", "fa": "درهم امارات", "symbol": "د.إ", "flag": "🇦🇪", "cc": "ae"},
    "TRY": {"en": "Turkish Lira", "fa": "لیر ترکیه", "symbol": "₺", "flag": "🇹🇷", "cc": "tr"},
    "CHF": {"en": "Swiss Franc", "fa": "فرانک سوئیس", "symbol": "CHF", "flag": "🇨🇭", "cc": "ch"},
    "CNY": {"en": "Chinese Yuan", "fa": "یوان چین", "symbol": "¥", "flag": "🇨🇳", "cc": "cn"},
    "JPY": {"en": "Japanese Yen", "fa": "ین ژاپن", "symbol": "¥", "flag": "🇯🇵", "cc": "jp"},
    "CAD": {"en": "Canadian Dollar", "fa": "دلار کانادا", "symbol": "C$", "flag": "🇨🇦", "cc": "ca"},
    "AUD": {"en": "Australian Dollar", "fa": "دلار استرالیا", "symbol": "A$", "flag": "🇦🇺", "cc": "au"},
    "NZD": {"en": "New Zealand Dollar", "fa": "دلار نیوزلند", "symbol": "NZ$", "flag": "🇳🇿", "cc": "nz"},
    "SGD": {"en": "Singapore Dollar", "fa": "دلار سنگاپور", "symbol": "S$", "flag": "🇸🇬", "cc": "sg"},
    "INR": {"en": "Indian Rupee", "fa": "روپیه هند", "symbol": "₹", "flag": "🇮🇳", "cc": "in"},
    "PKR": {"en": "Pakistani Rupee", "fa": "روپیه پاکستان", "symbol": "₨", "flag": "🇵🇰", "cc": "pk"},
    "IQD": {"en": "Iraqi Dinar", "fa": "دینار عراق", "symbol": "ع.د", "flag": "🇮🇶", "cc": "iq"},
    "SAR": {"en": "Saudi Riyal", "fa": "ریال عربستان", "symbol": "﷼", "flag": "🇸🇦", "cc": "sa"},
    "KWD": {"en": "Kuwaiti Dinar", "fa": "دینار کویت", "symbol": "د.ك", "flag": "🇰🇼", "cc": "kw"},
    "BHD": {"en": "Bahraini Dinar", "fa": "دینار بحرین", "symbol": ".د.ب", "flag": "🇧🇭", "cc": "bh"},
    "OMR": {"en": "Omani Rial", "fa": "ریال عمان", "symbol": "ر.ع.", "flag": "🇴🇲", "cc": "om"},
    "QAR": {"en": "Qatari Riyal", "fa": "ریال قطر", "symbol": "ر.ق", "flag": "🇶🇦", "cc": "qa"},
    "KRW": {"en": "South Korean Won", "fa": "وون کره جنوبی", "symbol": "₩", "flag": "🇰🇷", "cc": "kr"},
    "DKK": {"en": "Danish Krone", "fa": "کرون دانمارک", "symbol": "kr", "flag": "🇩🇰", "cc": "dk"},
    "SEK": {"en": "Swedish Krona", "fa": "کرون سوئد", "symbol": "kr", "flag": "🇸🇪", "cc": "se"},
    "NOK": {"en": "Norwegian Krone", "fa": "کرون نروژ", "symbol": "kr", "flag": "🇳🇴", "cc": "no"},
    "RUB": {"en": "Russian Ruble", "fa": "روبل روسیه", "symbol": "₽", "flag": "🇷🇺", "cc": "ru"},
    "THB": {"en": "Thai Baht", "fa": "بات تایلند", "symbol": "฿", "flag": "🇹🇭", "cc": "th"},
    "MYR": {"en": "Malaysian Ringgit", "fa": "رینگیت مالزی", "symbol": "RM", "flag": "🇲🇾", "cc": "my"},
    "HKD": {"en": "Hong Kong Dollar", "fa": "دلار هنگ‌کنگ", "symbol": "HK$", "flag": "🇭🇰", "cc": "hk"},
    "AFN": {"en": "Afghan Afghani", "fa": "افغانی افغانستان", "symbol": "؋", "flag": "🇦🇫", "cc": "af"},
    "AZN": {"en": "Azerbaijani Manat", "fa": "منات آذربایجان", "symbol": "₼", "flag": "🇦🇿", "cc": "az"},
    "AMD": {"en": "Armenian Dram", "fa": "درام ارمنستان", "symbol": "֏", "flag": "🇦🇲", "cc": "am"},
    "GEL": {"en": "Georgian Lari", "fa": "لاری گرجستان", "symbol": "₾", "flag": "🇬🇪", "cc": "ge"},
    "KGS": {"en": "Kyrgyzstani Som", "fa": "سوم قرقیزستان", "symbol": "сом", "flag": "🇰🇬", "cc": "kg"},
    "TJS": {"en": "Tajikistani Somoni", "fa": "سامانی تاجیکستان", "symbol": "SM", "flag": "🇹🇯", "cc": "tj"},
    "TMT": {"en": "Turkmenistani Manat", "fa": "منات ترکمنستان", "symbol": "T", "flag": "🇹🇲", "cc": "tm"},
    "SYP": {"en": "Syrian Pound", "fa": "لیر سوریه", "symbol": "£S", "flag": "🇸🇾", "cc": "sy"},
    "RON": {"en": "Romanian Leu", "fa": "لئو رومانی", "symbol": "lei", "flag": "🇷🇴", "cc": "ro"},
    "PLN": {"en": "Polish Zloty", "fa": "زلوتی لهستان", "symbol": "zł", "flag": "🇵🇱", "cc": "pl"},
    "CZK": {"en": "Czech Koruna", "fa": "کرون چک", "symbol": "Kč", "flag": "🇨🇿", "cc": "cz"},
    "HUF": {"en": "Hungarian Forint", "fa": "فورینت مجارستان", "symbol": "Ft", "flag": "🇭🇺", "cc": "hu"},
    "BGN": {"en": "Bulgarian Lev", "fa": "لو بلغارستان", "symbol": "лв", "flag": "🇧🇬", "cc": "bg"},
    "HRK": {"en": "Croatian Kuna", "fa": "کونا کرواسی", "symbol": "kn", "flag": "🇭🇷", "cc": "hr"},
    "RSD": {"en": "Serbian Dinar", "fa": "دینار صربستان", "symbol": "din.", "flag": "🇷🇸", "cc": "rs"},
    "UAH": {"en": "Ukrainian Hryvnia", "fa": "هریونیا اوکراین", "symbol": "₴", "flag": "🇺🇦", "cc": "ua"},
    "ISK": {"en": "Icelandic Krona", "fa": "کرون ایسلند", "symbol": "kr", "flag": "🇮🇸", "cc": "is"},
    "BRL": {"en": "Brazilian Real", "fa": "رئال برزیل", "symbol": "R$", "flag": "🇧🇷", "cc": "br"},
    "MXN": {"en": "Mexican Peso", "fa": "پزو مکزیک", "symbol": "MX$", "flag": "🇲🇽", "cc": "mx"},
    "ARS": {"en": "Argentine Peso", "fa": "پزو آرژانتین", "symbol": "AR$", "flag": "🇦🇷", "cc": "ar"},
    "CLP": {"en": "Chilean Peso", "fa": "پزو شیلی", "symbol": "CL$", "flag": "🇨🇱", "cc": "cl"},
    "COP": {"en": "Colombian Peso", "fa": "پزو کلمبیا", "symbol": "CO$", "flag": "🇨🇴", "cc": "co"},
    "ZAR": {"en": "South African Rand", "fa": "رند آفریقای جنوبی", "symbol": "R", "flag": "🇿🇦", "cc": "za"},
    "EGP": {"en": "Egyptian Pound", "fa": "پوند مصر", "symbol": "E£", "flag": "🇪🇬", "cc": "eg"},
    "NGN": {"en": "Nigerian Naira", "fa": "نایرا نیجریه", "symbol": "₦", "flag": "🇳🇬", "cc": "ng"},
    "MAD": {"en": "Moroccan Dirham", "fa": "درهم مراکش", "symbol": "د.م.", "flag": "🇲🇦", "cc": "ma"},
    "TND": {"en": "Tunisian Dinar", "fa": "دینار تونس", "symbol": "د.ت", "flag": "🇹🇳", "cc": "tn"},
    "KES": {"en": "Kenyan Shilling", "fa": "شیلینگ کنیا", "symbol": "KSh", "flag": "🇰🇪", "cc": "ke"},
    "IDR": {"en": "Indonesian Rupiah", "fa": "روپیه اندونزی", "symbol": "Rp", "flag": "🇮🇩", "cc": "id"},
    "PHP": {"en": "Philippine Peso", "fa": "پزو فیلیپین", "symbol": "₱", "flag": "🇵🇭", "cc": "ph"},
    "VND": {"en": "Vietnamese Dong", "fa": "دونگ ویتنام", "symbol": "₫", "flag": "🇻🇳", "cc": "vn"},
    "BDT": {"en": "Bangladeshi Taka", "fa": "تاکا بنگلادش", "symbol": "৳", "flag": "🇧🇩", "cc": "bd"},
    "LKR": {"en": "Sri Lankan Rupee", "fa": "روپیه سریلانکا", "symbol": "Rs", "flag": "🇱🇰", "cc": "lk"},
    "TWD": {"en": "New Taiwan Dollar", "fa": "دلار تایوان", "symbol": "NT$", "flag": "🇹🇼", "cc": "tw"},
    "JOD": {"en": "Jordanian Dinar", "fa": "دینار اردن", "symbol": "د.ا", "flag": "🇯🇴", "cc": "jo"},
    "LBP": {"en": "Lebanese Pound", "fa": "لیر لبنان", "symbol": "ل.ل", "flag": "🇱🇧", "cc": "lb"},
    "ILS": {"en": "Israeli Shekel", "fa": "شکل اسرائیل", "symbol": "₪", "flag": "🇮🇱", "cc": "il"},
    "UZS": {"en": "Uzbekistani Som", "fa": "سوم ازبکستان", "symbol": "сўм", "flag": "🇺🇿", "cc": "uz"},
    "KZT": {"en": "Kazakhstani Tenge", "fa": "تنگه قزاقستان", "symbol": "₸", "flag": "🇰🇿", "cc": "kz"},
}

POPULAR_CURRENCIES = [
    "IRR", "USD", "EUR", "GBP", "AED", "TRY", "SAR", "CAD",
    "AUD", "CHF", "JPY", "CNY", "INR", "KWD", "RON", "BRL",
]
