CURRENCIES = {
    "IRR": {"en": "Iranian Rial", "fa": "ریال ایران", "symbol": "﷼", "flag": "🇮🇷"},
    "USD": {"en": "US Dollar", "fa": "دلار آمریکا", "symbol": "$", "flag": "🇺🇸"},
    "EUR": {"en": "Euro", "fa": "یورو", "symbol": "€", "flag": "🇪🇺"},
    "GBP": {"en": "British Pound", "fa": "پوند بریتانیا", "symbol": "£", "flag": "🇬🇧"},
    "AED": {"en": "UAE Dirham", "fa": "درهم امارات", "symbol": "د.إ", "flag": "🇦🇪"},
    "TRY": {"en": "Turkish Lira", "fa": "لیر ترکیه", "symbol": "₺", "flag": "🇹🇷"},
    "CHF": {"en": "Swiss Franc", "fa": "فرانک سوئیس", "symbol": "CHF", "flag": "🇨🇭"},
    "CNY": {"en": "Chinese Yuan", "fa": "یوان چین", "symbol": "¥", "flag": "🇨🇳"},
    "JPY": {"en": "Japanese Yen", "fa": "ین ژاپن", "symbol": "¥", "flag": "🇯🇵"},
    "CAD": {"en": "Canadian Dollar", "fa": "دلار کانادا", "symbol": "C$", "flag": "🇨🇦"},
    "AUD": {"en": "Australian Dollar", "fa": "دلار استرالیا", "symbol": "A$", "flag": "🇦🇺"},
    "NZD": {"en": "New Zealand Dollar", "fa": "دلار نیوزلند", "symbol": "NZ$", "flag": "🇳🇿"},
    "SGD": {"en": "Singapore Dollar", "fa": "دلار سنگاپور", "symbol": "S$", "flag": "🇸🇬"},
    "INR": {"en": "Indian Rupee", "fa": "روپیه هند", "symbol": "₹", "flag": "🇮🇳"},
    "PKR": {"en": "Pakistani Rupee", "fa": "روپیه پاکستان", "symbol": "₨", "flag": "🇵🇰"},
    "IQD": {"en": "Iraqi Dinar", "fa": "دینار عراق", "symbol": "ع.د", "flag": "🇮🇶"},
    "SAR": {"en": "Saudi Riyal", "fa": "ریال عربستان", "symbol": "﷼", "flag": "🇸🇦"},
    "KWD": {"en": "Kuwaiti Dinar", "fa": "دینار کویت", "symbol": "د.ك", "flag": "🇰🇼"},
    "BHD": {"en": "Bahraini Dinar", "fa": "دینار بحرین", "symbol": ".د.ب", "flag": "🇧🇭"},
    "OMR": {"en": "Omani Rial", "fa": "ریال عمان", "symbol": "ر.ع.", "flag": "🇴🇲"},
    "QAR": {"en": "Qatari Riyal", "fa": "ریال قطر", "symbol": "ر.ق", "flag": "🇶🇦"},
    "KRW": {"en": "South Korean Won", "fa": "وون کره جنوبی", "symbol": "₩", "flag": "🇰🇷"},
    "DKK": {"en": "Danish Krone", "fa": "کرون دانمارک", "symbol": "kr", "flag": "🇩🇰"},
    "SEK": {"en": "Swedish Krona", "fa": "کرون سوئد", "symbol": "kr", "flag": "🇸🇪"},
    "NOK": {"en": "Norwegian Krone", "fa": "کرون نروژ", "symbol": "kr", "flag": "🇳🇴"},
    "RUB": {"en": "Russian Ruble", "fa": "روبل روسیه", "symbol": "₽", "flag": "🇷🇺"},
    "THB": {"en": "Thai Baht", "fa": "بات تایلند", "symbol": "฿", "flag": "🇹🇭"},
    "MYR": {"en": "Malaysian Ringgit", "fa": "رینگیت مالزی", "symbol": "RM", "flag": "🇲🇾"},
    "HKD": {"en": "Hong Kong Dollar", "fa": "دلار هنگ‌کنگ", "symbol": "HK$", "flag": "🇭🇰"},
    "AFN": {"en": "Afghan Afghani", "fa": "افغانی افغانستان", "symbol": "؋", "flag": "🇦🇫"},
    "AZN": {"en": "Azerbaijani Manat", "fa": "منات آذربایجان", "symbol": "₼", "flag": "🇦🇿"},
    "AMD": {"en": "Armenian Dram", "fa": "درام ارمنستان", "symbol": "֏", "flag": "🇦🇲"},
    "GEL": {"en": "Georgian Lari", "fa": "لاری گرجستان", "symbol": "₾", "flag": "🇬🇪"},
    "KGS": {"en": "Kyrgyzstani Som", "fa": "سوم قرقیزستان", "symbol": "сом", "flag": "🇰🇬"},
    "TJS": {"en": "Tajikistani Somoni", "fa": "سامانی تاجیکستان", "symbol": "SM", "flag": "🇹🇯"},
    "TMT": {"en": "Turkmenistani Manat", "fa": "منات ترکمنستان", "symbol": "T", "flag": "🇹🇲"},
    "SYP": {"en": "Syrian Pound", "fa": "لیر سوریه", "symbol": "£S", "flag": "🇸🇾"},
}

POPULAR_CURRENCIES = [
    "IRR", "USD", "EUR", "GBP", "AED", "TRY", "SAR", "CAD",
    "AUD", "CHF", "JPY", "CNY", "INR", "KWD",
]
